FROM quay.io/redhat-ai-services/huggingface-downloader:latest as base

# The model repo to download
ENV MODEL_REPO="RedHatAI/Qwen3-30B-A3B-speculator.eagle3"

# Download the necessary model files
RUN python3 download_model.py --model-repo ${MODEL_REPO} --allow-patterns "*.json" "*.bin"

# Final image containing only the essential model files
FROM quay.io/bjeon1/modelcar-catalog:Qwen3-30B-A3B-FP8-dynamic

COPY --from=base /models /models/Qwen3-30B-A3B-speculator.eagle3

# Set the user to 1001
USER 1001