FROM registry.access.redhat.com/ubi9/ubi-micro:9.6

# Copy the model files in multiple layers to avoid large image issues
COPY models/*.json /models/
COPY models/model-00001-of-00030.safetensors /models/
COPY models/model-00002-of-00030.safetensors /models/
COPY models/model-00003-of-00030.safetensors /models/
COPY models/model-00004-of-00030.safetensors /models/
COPY models/model-00005-of-00030.safetensors /models/
COPY models/model-00006-of-00030.safetensors /models/
COPY models/model-00007-of-00030.safetensors /models/
COPY models/model-00008-of-00030.safetensors /models/
COPY models/model-00009-of-00030.safetensors /models/
COPY models/model-00010-of-00030.safetensors /models/
COPY models/model-00011-of-00030.safetensors /models/
COPY models/model-00012-of-00030.safetensors /models/
COPY models/model-00013-of-00030.safetensors /models/
COPY models/model-00014-of-00030.safetensors /models/
COPY models/model-00015-of-00030.safetensors /models/
COPY models/model-00016-of-00030.safetensors /models/
COPY models/model-00017-of-00030.safetensors /models/
COPY models/model-00018-of-00030.safetensors /models/
COPY models/model-00019-of-00030.safetensors /models/
COPY models/model-00020-of-00030.safetensors /models/
COPY models/model-00021-of-00030.safetensors /models/
COPY models/model-00022-of-00030.safetensors /models/
COPY models/model-00023-of-00030.safetensors /models/
COPY models/model-00024-of-00030.safetensors /models/
COPY models/model-00025-of-00030.safetensors /models/
COPY models/model-00026-of-00030.safetensors /models/
COPY models/model-00027-of-00030.safetensors /models/
COPY models/model-00028-of-00030.safetensors /models/
COPY models/model-00029-of-00030.safetensors /models/
COPY models/model-00030-of-00030.safetensors /models/

# Set the user to 1001
USER 1001
