model:
  mode: uri
  uri: oci://quay.io/bjeon1/modelcar-catalog:gemma-4-31B-it-speculator.dflash
  args:
    - '--speculative-config={"model": "/mnt/models/gemma-4-31B-it-speculator.dflash", "num_speculative_tokens": 8, "method": "dflash"}'