FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4 as base

COPY requirements.txt .

# Install necessary Python dependencies
RUN microdnf -y install git git-lfs python3-pip && \
    microdnf clean all && \
    pip3 install -r requirements.txt

COPY download_model.py .
