FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6 as base

# Set the HF_TOKEN with --build-arg HF_TOKEN="hf_..." at build time
ARG HF_TOKEN

COPY requirements.txt .

# Install necessary Python dependencies
RUN microdnf -y install git git-lfs python3-pip && \
    microdnf clean all

USER 1001

RUN pip3 install -r requirements.txt

COPY download_model.py .
