# Base image for the modelcar Granite image
FROM quay.io/redhat-ai-services/huggingface-downloader:latest as base

# Set the HF_TOKEN with --build-arg HF_TOKEN="hf_..." at build time
ARG HF_TOKEN

# The model repo to download
ENV MODEL_REPO="mistralai/Mistral-7B-Instruct-v0.3"

# Download the necessary model files (config.json, tokenizer.json, and safetensors)
RUN python3 download_model.py --model-repo ${MODEL_REPO} \
    --allow-patterns "*.json" "model-*.safetensors" "tokenizer.model.v3" \
    --target-dir /models

# Final image containing only the essential model files
FROM registry.access.redhat.com/ubi9/ubi-micro:9.5

# Copy only the necessary model files from the base image
COPY --from=base /models /models

# Set the user to 1001
USER 1001
