FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6 as tiktoken-downloader

WORKDIR /tiktoken_encodings

RUN microdnf update -y && \
    microdnf install -y wget && \
    microdnf clean all

# tiktoken files are needed in disconnected environments
# https://docs.vllm.ai/projects/recipes/en/latest/OpenAI/GPT-OSS.html#troubleshooting
RUN wget -O o200k_base.tiktoken "https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken" && \
    wget -O cl100k_base.tiktoken "https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken"

FROM registry.access.redhat.com/ubi9/ubi-micro:9.6

# Copy the model files in multiple layers to avoid large image issues
COPY models/*.json /models/
COPY models/*.jinja /models/
COPY models/model-00000-of-00002.safetensors /models/
COPY models/model-00001-of-00002.safetensors /models/
COPY models/model-00002-of-00002.safetensors /models/

# Copy the tiktoken files from the tiktoken-downloader image
COPY --from=tiktoken-downloader /tiktoken_encodings /models/tiktoken_encodings

# Set the user to 1001
USER 1001
