# Base image for the modelcar Granite image
FROM quay.io/redhat-ai-services/huggingface-downloader:latest as base

# The model repo to download
ENV MODEL_REPO="beomi/Llama-3-Open-Ko-8B"

# Download the necessary model files
RUN python3 download_model.py --model-repo ${MODEL_REPO}

# Final image containing only the essential model files
FROM registry.access.redhat.com/ubi9/ubi-micro:9.6

# Copy the model files in multiple layers to avoid large image issues
COPY models/*.json /models/
COPY models/model-00001-of-00006.safetensors /models/
COPY models/model-00002-of-00006.safetensors /models/
COPY models/model-00003-of-00006.safetensors /models/
COPY models/model-00004-of-00006.safetensors /models/
COPY models/model-00005-of-00006.safetensors /models/
COPY models/model-00006-of-00006.safetensors /models/

# Set the user to 1001
USER 1001






